name: open_stellar_wars
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flame: ^1.26.0
  logger: ^2.5.0
  connectivity_plus: ^6.1.1
  shared_preferences: ^2.3.4
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # image asset name JSON
    - assets/data/img_asset_names.json
    
    - assets/images/player_1.png
    # coin images
    - assets/images/coin.jpg
    - assets/images/coins/coin_flip.jpg
    - assets/images/coins/blue.jpg
    - assets/images/coins/red.jpg
    - assets/images/coins/gold.jpg
    - assets/images/coins/rocket_coin.jpg

    # coin - golds
    - assets/images/coins/golds/gold_coin_idle.png
    - assets/images/coins/golds/gold_coin_sheet.png
    - assets/images/coins/golds/gold_coin_hit_ground.png

    # coin - silvers
    - assets/images/coins/silvers/silver_coin_sheet.png
    - assets/images/coins/silvers/silver_coin_idle.png
    - assets/images/coins/silvers/silver_coin_hit_ground.png

    # obstacle images
    - assets/images/rock.jpg
    - assets/images/obstacles/road_cone.png
    # background downward move
    - assets/images/backgrounds/dark_space.png

  #   - images/a_dot_ham.jpeg    
    # about me data
    - assets/data/developer_profile.json
    - assets/images/profile.jpeg

    # enemy images
    ###### swarm fighters
    - assets/images/enemies/swarm_fighters/swarm_fighter.png

    ###### plasma fighters
    - assets/images/enemies/plasma_fighters/plasma_fighter.png

    # player sprite
    - assets/images/players/player_sprite.jpg
    - assets/images/players/walk_sheet.png
    - assets/images/players/car_sprite.png

    # player - bullets
    - assets/images/players/bullets/normal_bullet.png

    # explosions - enemy
    - assets/images/explosions/enemy_explode.png

    # player spaceship
    - assets/images/players/spaceships/spaceship_idle.png
    - assets/images/players/spaceships/spaceship_flying.png

    # player kitty
    - assets/images/players/kitties/kitty_jumping.png
    - assets/images/players/kitties/kitty_jump.png
    - assets/images/players/kitties/kitty_stand.png
    - assets/images/players/kitties/kitty_post_jump.png
    - assets/images/players/kitties/kitty_upward.png
    - assets/images/players/kitties/kitty_idle.png
    - assets/images/players/kitties/kitty_move_left.png
    - assets/images/players/kitties/kitty_move_right.png

    # surface to lands
    ###### trees
    - assets/images/surfacetolands/trees/tree_spawning.png

    ###### stones
    - assets/images/surfacetolands/stones/stone_spawning.png

    # obstacles
    ###### fire obstacles
    - assets/images/obstacles/fires/fire_obstacle.png

    # powerups
    ###### rockets
    - assets/images/powerups/rockets/rocket.png



  fonts:
    - family: KhmerOS
      fonts:
        - asset: assets/fonts/KhmerOS.ttf
    - family: KhmerOS-Reg
      fonts:
        - asset: assets/fonts/KhmerOSNew-Regular.ttf      
    - family: KhmerOS-Regular
      fonts:
        - asset: assets/fonts/KhmerOSNew-Regular.ttf
    - family: KhmerOS-Bold
      fonts:
        - asset: assets/fonts/KhmerOSNew-Bold.ttf
          weight: 700
    - family: KhmerOSMouli
      fonts:
        - asset: assets/fonts/KhmerOSMoulpali.ttf
        - asset: assets/fonts/KhmerOSMoulLight.ttf
        - asset: assets/fonts/KhmerOSMetalchrieng.ttf
        - asset: assets/fonts/KhmerOSContent-Regular.ttf
        - asset: assets/fonts/KhmerOSContent-Bold.ttf    
  # font OpenSans
    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
